# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb32fe74e6ba4511e691ac57e71e05262010b05c4c82be8e3c08e7ab1c97941c49e54a825186f8b73d810aca99d20554e38585a06f260d3478bfc1bd1c278d21

test:
  secret_key_base: ae53961c59b2c2f817685482e100e02140efd605a1bda4d9acb940f95bb3884f1b4be7be38c7503eb8c551c4404d62e3a309792c80e8d9f26fefa6f17add4fb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
